config/routes.rb
Golf::Application.routes.draw do
  
  get "pages/rules"

  devise_for :users

  root :to => 'problems#index'
  
  resources :users
  resources :submissions do
    member do 
      put 'correct'
      put 'incorrect'
    end
  end  
  
  resources :problems do
    put 'close', :on => :member
    resources :submissions, :only => [:create, :destroy]
  end
  
  
  

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :submissions, :dependent => :destroy
  
  validates :title, :presence => true
  validates :description, :presence => true
  validates :par_score, :presence => true, :numericality => true
  
  attr_accessible :title, :description, :comment, :par_score, :language, :current_problem, :sample_output, :deadline
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :problem
  
  attr_accessible :script
  
  validates :user_id, :presence => true
  validates :problem_id, :presence => true    
  
  default_scope :order => 'submissions.created_at desc'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :submissions, :dependent => :destroy       

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
  def has_submitted?(problem)
    submissions = self.submissions.find_all{|submission| submission.problem_id = problem.id}
    !submissions.empty?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def rules
  end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
    @current_problems = Problem.find(:all, :conditions => ["current_problem = ?", true])
    @old_problems = Problem.find(:all, :conditions => ["current_problem = ?", false])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])
    @submissions = @problem.submissions.all
    @current_user_has_submitted = !@problem.current_problem? ||(current_user && (current_user.admin? || current_user.has_submitted?(@problem)))
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, :notice => 'Problem was successfully created.' }
        format.json { render :json => @problem, :status => :created, :location => @problem }
      else
        format.html { render :action => "new" }
        format.json { render :json => @problem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, :notice => 'Problem was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @problem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :ok }
    end
  end
  
  def close
    problem = Problem.find(params[:id])
    score_list = Array.new
    
    problem.submissions.each do |submission|
      score_list.push(submission.script.length)
    end
    
    score_list.sort!
    total = score_list.size
    
    problem.submissions.each do |submission|
      score = total - score_list.index(submission.script.length)
      submission.user.score += score
      submission.user.save
    end
    problem.update_attribute(:current_problem, false)
    redirect_to problem
  end
  
  protected
    def record_not_found
      flash[:error] = 'The problem you requested could not be found'
      redirect_to root_url
    end
    
    def make_current
      Problem.all.each do |problem|
        problem.current = false
        problem.save
      end
      @problem = Problem.find(params[:id])
      @problem.current = true
      @problem.save
    end
  
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @submission = Submission.find(params[:id])
    @current_user_has_submitted = !@submission.problem.current_problem? || (current_user && (current_user.admin? || current_user.has_submitted?(@submission.problem)))
  end
  
  def create
    @problem = Problem.find(params[:problem_id])
    @problem.submissions.each do |submission|
      submission.destroy if submission.user.id == current_user.id
    end
    @submission = @problem.submissions.build(params[:submission])
    @submission.user = current_user
    @submission.script = @submission.script.gsub(/\r\n/, "\n")
    @submission.save
    
    respond_to do |format|
      if @submission.save
        format.html { redirect_to(@problem, :notice => 'Submission was successfully created.') }
      else
        format.html { redirect_to(@problem, :notice => 'There was an error saving your submission (empty submission or submission way to long).') }
      end
    end
  end
  
  def destroy
    @submission = current_user.submissions.find(params[:id])
    @problem = Problems.find(params[:problem_id])
    @submission.destroy
    
    redirect_to @problem
  end
  
  def correct
    submission = Submission.find(params[:id])
    submission.update_attribute(:correct, true)
    redirect_to submission
  end
  
  def incorrect
    submission = Submission.find(params[:id])
    submission.update_attribute(:correct, false)
    redirect_to submission
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    @users.sort!{|a,b| b.score <=> a.score}
  end
  
  def show
    @user = User.find(params[:id])
    @submissions = @user.submissions
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header id="page_header">
  <h1>
    <!-- <%= logo = image_tag("images/logo.png", :alt => "Code Golf", :class => "round") %> -->
    <% logo = "Middlebury Code Golf"%>    
    <%= link_to logo, root_path %>
  <nav id="nav_user" class = "round light">
    <ul>
        <li><%= link_to "Rules", pages_rules_path %>  </li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, user_path(current_user) %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>        
      <% end %>
    </ul>
  </nav>
  </h1>
</header>

app/views/layouts/_intro.html.erb
<div class="round box" id="introduction">
  <strong>Welcome</strong> to CodeGolf. The premise is simple. There will be a new problem every week and the goal is to solve that problem in the least number of characters. The player with the shortest correct solution at the end of the week wins.
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="round box light">
  <div id="links">
    <div><%= link_to "Home", problems_path %></div>
    <div><%= link_to "Players", users_path %></div>        
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golf</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="container">
    <%= render 'layouts/header'%>
    <br>
    <%= render 'layouts/sidebar' %>
    
    <div id="content">

      <section id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </section>

      <%= yield %>
    </div>
    


  </div>


</body>
</html>

app/views/pages/rules.html.erb
<div class="title">Rules</div>
<div class="round green box light">
  <ol id="rules">
    <li>A new problem will be posted every week.</li>
    <li>You can submit multiple solutions to each problem. Each new 
      solution will overwrite the previous one.</li>
    <li>Your solution must not access any resources outside the code. No access to the internet, 
      other files, etc. As a rule of thumb, if the administrator can copy the text of your submitted 
      code and run it on a computer without internet access and produce the desired output, it will be accepted. </li>
    <li>Your score will be equal to the additive inverse of the rank of your best submission. That is, if there are 50 submissions and you submit the 5th shortest solution you will receive 50 - 5 + 1 = 46 points.</li>
    <li>The problem will be closed on the day of the deadline and the score from each 
      players submission will be added to his/her overall score</li>
    <li>As with everything at Middlebury, the honor code applies. Some of the problems posted here
      are already pretty popular and may have solutions posted elsewhere. </li>      
    <li>For more information, contact <%= mail_to "armaansarkar@gmail.com"%></li>
    <li>Happy golfing!</li>
  </ol>
</div>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :sample_output %><br />
    <%= f.text_area :sample_output %>
  </div>
  <div class="field">
    <%= f.label :par_score %><br />
    <%= f.number_field :par_score %>
  </div>  
  <div class="field">
    <%= f.label :current_problem %><br />
    <%= f.check_box :current_problem %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/_problem.html.erb
<div class="round box link old_problem">
  <div><%= link_to problem.title, problem %> in <%= problem.language %></div>
  <!-- <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
  <td><%= link_to 'Destroy', problem, :confirm => 'Are you sure?', :method => :delete %></td> -->
</div>

app/views/problems/_problem_full.html.erb
<div class="round box link problem_with_description">
  <div class="bold"><%= link_to "#{problem.title} in #{problem.language}", problem %></div>
  <div class="subtext">Deadline: <%= problem.deadline.strftime("%A, %B %d at 11:59 pm") %></div>
  <%= problem.description %>
</div>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<div class="container">
  <%= render :partial => 'layouts/intro'%>
  <div id="problems">
    <% if !@current_problems.empty? %>
      <div class="title">
        Current Problem
      </div>
      <% @current_problems.each do |problem| %>
        <%= render :partial => 'problem_full', :locals => { :problem => problem } %>
      <% end %>
    <% end %>
    <% if !@old_problems.empty? %>
      <div class="title">
        Old Problems
      </div>
      <% @old_problems.each do |problem| %>
        <%= render :partial => 'problem', :locals => { :problem => problem } %>
      <% end %>
    <% end %>
    <br />
    <% if !current_user.nil? && current_user.admin? %>
      <div class="round button"><%= link_to 'New Problem', new_problem_path %></div>
    <% end %>
  </div>
</div>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<section id="problembody">
  <%= render :partial => 'problem_full', :locals => { :problem => @problem } %>
</section>

<% if @problem.comment %>
  <div class="round box light">
    <%= simple_format(@problem.comment) %>
  </div>
<% end %>

<div class="title">Sample Output</div>
<code>
  <pre id="sample_output" class="box"><%= @problem.sample_output %></pre>
</code>

<% if @problem.current_problem? %>
  <div class="title">Submit a solution</div>
  <problem class="submission newsubmission">
    <% if user_signed_in? %>
      <div class="round box light">
        <%= render :partial => 'submissions/form'%>
      </div>
    <% end %>
  </problem>
<% end %>

<% if !current_user.nil? && current_user.admin? %>
  <dive class="button">
    <%= link_to "Close Problem", close_problem_path(@problem), :method => :put %>
  </div>
<% end %>

<div class="title">Submitted solutions</div>
  <% @submissions.each do |submission| %>
    <%= render :partial => 'submissions/submission', :object => submission %>
  <% end %>
 </div>

<% if !current_user.nil? && current_user.admin? %>
  <%= link_to 'Edit', edit_problem_path(@problem) %>
<% end %>

app/views/submissions/_form.html.erb
<%= form_for [@problem, current_user.submissions.new] do |f| %>  
  <div id="submit"><%= f.text_area :script, :placeholder => "paste your solution in here" %></div>
  <div><%= f.submit "Submit solution" %></div>
<% end %>

app/views/submissions/_submission.html.erb
<div class="round box light link">
  <div><%= link_to submission.problem.title, submission %>
  <span class="subtext">
  <% if submission.correct.nil? %>
    (Unverified)
  <% elsif submission.correct %>
    (Correct)
  <% else %>
    (Incorrect)
  <% end %>
  </span>
  </div>
  <div class="subtext">by <%= submission.user.name %> <% if @current_user_has_submitted %>in <%= submission.script.length %> characters <% end %></div>
</div>

app/views/submissions/show.html.erb
<section id="submission">
  <%= render :partial => 'submission', :object => @submission %>
  <% if @submission.user.id == current_user.id || current_user.admin? || !@submission.problem.current_problem %>
    <br>
    <div class="title">Code</div>
    <pre>
      <div id="code_block" class="box"><%= @submission.script %></div>      
    </pre>  
  <% end %>
  <% if current_user.admin? %>
    <span class="button"><%= link_to "correct", correct_submission_path, :method => :put %></span>
    <span class="button"><%= link_to "incorrect", incorrect_submission_path, :method => :put %></span>
  <% end %>
<section>

app/views/users/_user.html.erb
<div>
  <table id = "user" class = "round box main link">
    <tr>
    <td><%= link_to user.name, user %></td>
    <td class="right"><%= user.score %></td>
    </tr>
  </table>
</div>

app/views/users/index.html.erb
<section id="all_users">
  <table id="title" class="title"><tr>
    <td>Player</td><td class="right">Score</td>
  </tr></table>
  <% @users.each do |user| %>
    <% if !user.admin? %>
      <%= render :partial => 'user', :object => user %>
    <% end %>
  <% end %>
</section>

app/views/users/show.html.erb
<section id="user_profile">
  <%= render :partial => 'user', :object => @user%>
  <br>
  <% if !@submissions.empty? %>
    <div class="title">Submissions</div>
      <% @submissions.each do |submission| %>
        <%= render :partial => 'submissions/submission', :object => submission %>
      <% end %>
    <% end %>
</section>